sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t eunhomoon/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true eunhomoon/docker-react-app npm run test -- --coverage

# after_success:
#   - echo "Test success"

deploy:
  provider: elasticbeanstalk
  edge: true
  region: 'ap-northeast-2'
  app: 'docker-react'
  env: 'Docker-react-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-2-036995284236'
  bucket_path: 'docker-react'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
