name: Docker React App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build Docker image
        run: |
          echo "start creating an image with dockerfile"
          docker build -t eunhomoon/docker-react-app -f Dockerfile.dev .

      - name: Run tests
        run: |
          docker run -e CI=true eunhomoon/docker-react-app npm run test -- --coverage

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          application_name: docker-react-app
          enviroment_name: Docker-react-app-env
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-northeast-2

      - name: Deploy to Elastic Beanstalk
        run: |
          echo "Deploying to Elastic Beanstalk..."
          eb init docker-react-app --region ap-northeast-2
          eb setenv CI=true
          eb deploy --staged
